# This file is an example of /etc/nix/nix.conf to build the image.

build-users-group = nixbld

# For cross-compile (not working)
# https://discourse.nixos.org/t/how-to-configure-qemu-binfmt-wrapper-on-a-non-nixos-machine/7879/8
# extra-platforms = aarch64-linux
# extra-sandbox-paths = /usr/bin/qemu-aarch64
# https://github.com/nix-community/nixos-generators/issues/83
# system-features = nixos-test benchmark big-parallel kvm

# For within an arm64 or emulated arm64 vm with `-machine virt,virtualization=on`:
# (grabbed from .github/workfllows/image.yml)
system-features = nixos-test benchmark big-parallel kvm

