name: Build image

on:
  # schedule:
  #   - cron: '0 0 * * 0'
  workflow_dispatch:
  push:
    branches:
      - trunk

jobs:
  matrix:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'trunk'
      #- uses: cachix/install-nix-action@v31
      #  with:
      #    nix_path: nixpkgs=channel:nixos-unstable
      - run: ./.github/get-channels.sh
        id: set-matrix
  update:
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        arch:
        - id: aarch64
          os: ubuntu-22.04-arm
        # - id: x86_64
        #   os: ubuntu-22.04
        nixos: ${{ fromJson(needs.matrix.outputs.matrix) }}
    permissions:
      # Give the default GITHUB_TOKEN write permission to create releases
      contents: write
    runs-on: ${{ matrix.arch.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'trunk'
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-${{ matrix.nixos }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          # explicitly enable sandbox
          extra_nix_config: |
            sandbox = true
            system-features = nixos-test benchmark big-parallel kvm
      - uses: cachix/cachix-action@v16
        with:
          name: nix-avf-osz
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      # path /home/runner should have permissions 755, but had permissions 750. Consider running 'chmod o+rx /home/runner'.
      - run: chmod o+rx /home/runner
      - run: ./.github/build.sh ${{ matrix.nixos }} ${{ matrix.arch.id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: image-${{ matrix.nixos }}-${{ matrix.arch.id }}
          path: image-${{ matrix.nixos }}-${{ matrix.arch.id }}.tar.gz
